### ISSUE TITLE
ginormous image sideloads when using "enlargement"

### ISSUE THREAD

**Issue by tamw-wnet** [OpenPublicMedia/nprapi-wordpress#21]
I've been noticing stories like this one API ID 1134823910 
https://www.npr.org/2022/11/17/1134823910/nador-morocco-spain-migration-immigrants
where the primary image has an 'enlargement' that is 10MB+, and that's what the plugin sideloads.  On a slower server, this will cause an error or timeout while trying to download and manipulate the image.

Should we automatically add an 's=6' parameter to any of these enlargments so we get an image that is still quite large but not egregious?   I can do so @jwcounts just looking for your thoughts.

**Comment by jwcounts** [comment]
I would say to look for the enlargement image crop and check the width first. If it's over 1500-2000px, then add the 's=6'.

**Comment by tamw-wnet** [comment]
#22 resolves the issue.
