### ISSUE TITLE
PHP error on Line 636 

### ISSUE THREAD

**Issue by RayHollister** [OpenPublicMedia/nprapi-wordpress#23]
I'm getting the following error on /wp-admin/post-new.php?post_type=npr_story_post

`Warning: Attempt to read property "status" on null in /code/wp-content/plugins/npr-story-api/push_story.php on line 636`
![image](https://user-images.githubusercontent.com/369131/215211767-1456d2a9-67a1-47d7-94e7-272aa288e794.png)

Wordpress version | 6.1.1
PHP version | 8.0.27

I'm working on it right now, and will let you know if/when I find the fix.

**Comment by RayHollister** [comment]
So, I tossed the error and lines 636-646 into ChatGPT and here's what it kicked out:

```
if (isset($post) && !empty($date)) {
    if ('publish' === $post->status ) {
        $timezone = get_option( 'gmt_offset' );
        $datetime = date_create( $date, nprstory_get_datetimezone() );
        $time = explode( ':', $time );
        $datetime->setTime( $time[0], $time[1] );
        $value = date_format( $datetime, DATE_ATOM );
        update_post_meta( $post_ID, '_nprone_expiry_8601', $value );
    } else {
        delete_post_meta( $post_ID, '_nprone_expiry_8601' );
    }
}
```

Looks like it's working on my local server!

**Comment by jwcounts** [comment]
Wow, this completely went under my radar. This has been fixed in the latest release.
