### ISSUE TITLE
Renaming "master" to "main"

### ISSUE THREAD

**Issue by tamw-wnet** [OpenPublicMedia/nprapi-wordpress#5]
Since this is a relatively new repository with very few followers, I suggest we follow updated git best practice and make our default branch 'main'.   I suggest we do this before we resubmit this plugin to the Wordpress plugin directory.

**Comment by tamw-wnet** [comment]
@jwcounts @davidmpurdy lemme know if you concur.  We should probably handle #1 first since it's pending.

**Comment by jwcounts** [comment]
Sounds good to me

**Comment by jwcounts** [comment]
Went ahead and did it
