### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by tamw-wnet** [OpenPublicMedia/nprapi-wordpress#6]
@jwcounts @davidmpurdy I propose once we merge in #1 we make a new release, 1.9  Or are there other pending bugfixes we should try and get in with it?

Whenever we do, I'll commit an update to the README listing the updates as part of the release.

**Comment by jwcounts** [comment]
Yes, sorry, finally pulling my head out and looking at this. I am cool with updating to 1.9 after PRs are merged. I'd like to merge in the 2 pending ones, and I have a couple of small changes to merge in as well after.

**Comment by tamw-wnet** [comment]
@jwcounts you've actually done more of the cleanup and maintenance here than anyone, do you want to take on submitting the update to the wordpress.org plugin repo?  I'm happy to do so as well, I think there's going to be a fair amount of back and forth since we're changing ownership of the plugin.

**Comment by jwcounts** [comment]
That's fine with me. I haven't done it before but I will work on it on Monday.
